TutionFee/urls.py
from django.conf.urls import url
from . import views

app_name = 'TutionFee'

urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^home/(?P<subject>\w+)/$', views.subject_wise, name='subject_wise'),
    url(r'^home/(?P<subject>\w+)/(?P<division>\w+)/$', views.division_wise, name='division_wise'),
]

UniversityTutionFee/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('TutionFee.urls')),
]

TutionFee/models.py
from django.db import models


class Information(models.Model):
    u_name = models.CharField(max_length=200, blank=True, null=True)
    short_name = models.CharField(max_length=50, blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return self.u_name


class Cost(models.Model):
    u_inf = models.ForeignKey(Information)
    subject = models.CharField(max_length=50,blank=True,null=True)
    cost = models.IntegerField(blank=True,null=True)

    def __str__(self):
        return self.subject


# pass:tuhin123
# c = Cost.objects.filter(subject='CSE') i.u_inf.u_name,i.u_inf.city,i.cost
# inf = Information.objects.filter(city='dhaka')
# a = cost.objects.filter(pk__in=li)

TutionFee/forms.py
from django import forms

class RangeForm(forms.Form):
    min_cost = forms.IntegerField()
    serial = forms.IntegerField(required=False, default='0', widget=forms.TextInput())

TutionFee/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .scrapy import cost_tu
from .models import Cost,Information
from django.db.models import Q

divisions_list = ['Dhaka', 'Chittagong', 'Rajshahi', 'Barisal', 'Khulna',
                     'Mymensingh', 'Rangpur', 'Sylhet']
def home(request):
    subject_list = ['CSE', 'LLB', 'BBA', 'EEE', 'ENGLISH',]
    context = {
        'subject_list': subject_list,
        'All': 'All',
    }
    return render(request, 'TutionFee/home.html', context)

def subject_wise(request,subject):
    if request.GET.get('high'):
        u_cost = Cost.objects.filter(subject=subject).order_by("-cost")
        active="h"
    elif request.GET.get('low'):
        u_cost = Cost.objects.filter(subject=subject).order_by("cost")
        active="l"
    elif request.GET.get('normal'):
        u_cost = Cost.objects.filter(subject=subject)
        active="n"
    else:
        u_cost = Cost.objects.filter(subject=subject)
        active="none"
    context = {
        'u_cost': u_cost,
        'divisions_list': divisions_list,
        'subject': subject,
        'active': active,
    }
    return render(request, 'TutionFee/tuition.html', context)
def max_min(self,sub):
     if request.GET.get('high'):
         u_cost = Cost.objects.filter(subject=subject).order_by("-cost")
         active="h"
     elif request.GET.get('low'):
         u_cost = Cost.objects.filter(subject=subject).order_by("cost")
         active="l"
     elif request.GET.get('normal'):
         u_cost = Cost.objects.filter(subject=subject)
         active="n"
     else:
         u_cost = Cost.objects.filter(subject=subject)
         active="none"
     return self.u_cost
     return self.active

def division_wise(request, subject, division):
    obj = cost_tu()
    obj.cse()
    min_price = request.GET.get("lower")
    max_price = request.GET.get("higher")
    print("hb h",min_price)

    if request.GET.get('high'):
        u_cost = Cost.objects.filter(subject=subject).order_by("-cost")
        active="h"
    elif request.GET.get('low'):
        u_cost = Cost.objects.filter(subject=subject).order_by("cost")
        active="l"
    elif request.GET.get('normal'):
        u_cost = Cost.objects.filter(subject=subject)
        active="n"
    else:
        u_cost = Cost.objects.filter(subject=subject)
        active="none"
    if min_price or max_price:
        u_cost = Cost.objects.filter(subject=subject,cost__range=(int(min_price),int(max_price)))

    context = {
        'subject': subject,
        'divisions_list': divisions_list,
        'division': division,
        #'u_cost': Cost.objects.filter(subject=subject),
        'u_cost': u_cost,
        'active': active,
    }

    return render(request, 'TutionFee/tuition.html', context)

# max_min = Cost.objects.filter(subject=subject,cost__range=(min_price,max_price))

TutionFee/templates/TutionFee/home.html
{% extends 'TutionFee/base.html' %}
{% block  home_active%} active {% endblock %}
{% block title_name %} Home {% endblock %}
{% block back_color %}back_color{% endblock %}
{% block body %}
    <div class="container back_color">
        <div class="row  mx-auto justify-content-around " style="text-align: center">
            {% for subject in subject_list %}
                <div class="col-md-4 col-sm-12  mt-5 py-3 " style="text-align: center">
                  <a class=" btn btn-outline-info btn-lg " href="{% url 'TutionFee:subject_wise' subject  %}" role="button"> {{ subject }}</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% comment %}
    <a href="{% url 'TutionFee:subject' i %}"></a>
    {% for i in subject_list%}
            <p>{{ i }}</p><br>
        {% endfor %}
        <p>{{ subject_number }}</p>
{% endcomment %}

TutionFee/templates/TutionFee/tuition.html
{% extends 'TutionFee/base.html' %}
{% block title_name %} Tuition-Fee {% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row sticky-top">
        <div class="col bg-primary " >
            <h4 class="text-white text-center  p-3">{{ subject }} ({{ division }} division)</h4>
        </div>
    </div>
    <div class="row">
        <!-- Division menu link -->
        <div class="col-md-3 bg-faded ">
            <div class="d-flex flex-column mt-2">
                <a href="{% url 'TutionFee:subject_wise' subject  %}" class="btn bg-info text-white btn-lg btn-block">
                    All division
                </a>
                {% for divisions in divisions_list %}
                    {% comment %}<div class=" bg-info text-white p-2 mt-2 text-center ">{{ division }}</div>{% endcomment %}
                    <a href="{% url 'TutionFee:division_wise' subject divisions|lower %}" class="btn bg-info text-white btn-lg btn-block">
                        {{ divisions }}
                    </a>
                {% endfor %}
            </div>
        </div>
        <!--  Show detaile in Table -->
        <div class="col-md-6 ">
            <table class="table ">
                <thead>
                    <tr>
                      <th>#</th>
                      <th>University Name</th>
                      <th>Cost</th>
                      <th>City</th>
                    </tr>
                </thead>
                <tbody>
                {% if division%}
                    {% for ob in  u_cost %}
                        <tr>
                        {% if ob.u_inf.city == division%}
                            <td>{{ forloop.counter }}</td>
                            <td>{{ ob.u_inf.u_name|title }}</td>
                            <td>{{ ob.cost }} Tk</td>
                            <td>{{ ob.u_inf.city|capfirst }}</td>
                        {% endif %}
                        </tr>
                    {% endfor %}
                {% else %}
                    {% for foo in  u_cost %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ foo.u_inf.u_name}}</td>
                            <td>{{ foo.cost}} Tk</td>
                            <td>{{ foo.u_inf.city|capfirst }}</td>
                        </tr>
                    {% endfor %}
                {% endif %}
                </tbody>
            </table>
        </div>
        <div class="col-md-3 bg-faded">
            <h3> Filter By Cost</h3>
            <p><b>higher :</b> Higher cost tuition fee</p>
            <p><b>lower :</b> Lower cost tuition fee</p>
            <p><b>normal :</b> Normal from tuition fee</p>
        <form method='get' action=''>
                    <input type="submit"
                    {% if active == "n" %}
                    class="btn btn-danger btn-lg btn-block mt-2 active"
                    {% else %}
                    class="btn btn-info btn-lg btn-block mt-2"
                    {% endif %}
                    value="Normal"  name="normal" >

                    <input type="submit" {% if active == "h" %}
                    class="btn btn-danger btn-lg btn-block mt-2 active"
                    {% else %}
                    class="btn btn-info btn-lg btn-block mt-2"
                    {% endif %}
                    value="higher" name="high" >

                    <input type="submit"{% if active == "l" %}
                    class="btn btn-danger btn-lg btn-block mt-2 active"
                    {% else %}
                    class="btn btn-info btn-lg btn-block mt-2"
                    {% endif %}
                     " value="lower" name="low" checked>

        </form>
        <form method='get' action=''>
            <input type="text" name="lower" > <b>to</b>
            <input type="text" name="higher" >
            <input type="submit" value="click">
        </form>
        </div>
        </div>
</div>
{% endblock %}